GET https://api.arcane.no/ping

###

GET https://api.arcane.no/utc
Authorization: Bearer

###

GET https://api.arcane.no/whoami
Authorization: Bearer

###

OPTIONS https://api.arcane.no
Origin: https://arcane.no
Access-Control-Request-Method: GET

###



