### Open to internet

GET https://api.arcane.no/ping

### Open on app. Secured on gateway.

GET https://api.arcane.no/utc
Authorization: Bearer <firebase-id-token>

### Secured on app and gateway.

GET https://api.arcane.no/whoami
Authorization: Bearer <firebase-id-token>

### apple

GET https://api.arcane.no/firebase-custom-token
Authorization: Bearer <apple-id-token>

### oauth2-provider-emulator keys

GET http://localhost:8080/auth/keys

### oauth2-provider-emulator idToken

GET http://localhost:8080/id-token
Content-Type: application/json

{
  "subject": "test",
  "email": "test@arcane.no"
}