POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { legalTextCollection (limit:10) { items { titleOfLegalText contentOfLegalText { json } sys { id spaceId environmentId publishedVersion } } } }"
}

###

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { legalTextCollection (where: { titleOfLegalText: \"platform.termsAndConditions\" }, limit:10) { items { titleOfLegalText sys { id spaceId environmentId publishedVersion } } } }"
}

###

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { pageWeeklyUpdateCollection (limit:3) { items { name content { json } sys { environmentId } } } }"
}

###

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { pageCollection (order:[sys_firstPublishedAt_ASC],limit: 5) { items { title slug content { ... on PageWeeklyUpdate { subtitle content {json } image { fileName title description url } tagsCollection { items { name } } authorsCollection { items { name } } publishDate sys { id } } } } } }"
}

###

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { pageCollection (limit: 300) { items { content { ... on PageWeeklyUpdate { sys { id } } } } } }"
}

###

PUT https://api.contentful.com/spaces/{space_id}/entries/{entry_id}/published
Authorization: Bearer
X-Contentful-Version: 6