### Get legal entry metadata for given T&C ID

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { legalTextCollection (where: { titleOfLegalText: \"platform.termsAndConditions\" }, limit:10) { items { titleOfLegalText sys { id spaceId environmentId publishedVersion } } } }"
}

### Get limit 5 research pages with child articles with its rich text content and metadata

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { pageCollection (order:[sys_firstPublishedAt_ASC],limit: 5) { items { title slug  sys { id publishedAt } content { ... on PageWeeklyUpdate { subtitle content {json } image { fileName title description url } tagsCollection { items { name } } authorsCollection { items { name image { fileName title description url } } } publishDate } } } } }"
}

### Get limit 5 research pages with child articles without its rich text content

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { pageCollection (order:[sys_firstPublishedAt_ASC],limit: 10) { items { title slug  sys { id publishedAt } content { ... on PageWeeklyUpdate { subtitle image { fileName title description url } tagsCollection { items { name } } authorsCollection { items { name image { fileName title description url } } } publishDate } } } } }"
}

### Get all page ids along with first publishedAt

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { pageCollection (limit: 300) { items { sys { id publishedAt } } } }"
}

### Get all page slugs along with first publishedAt for sitemap

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { pageCollection (limit: 11000) { items { slug sys { publishedAt } } } }"
}

### Get article and its parent page

POST https://graphql.contentful.com/content/v1/spaces/{space_id}
Content-Type: application/json
Authorization: Bearer

{
  "query": "query { pageWeeklyUpdateCollection (limit: 1) { items { subtitle publishDate sys { id } linkedFrom { pageCollection { items { title slug sys { id publishedAt } } } } } } }"
}