PUT https://api.k33.com/apps/invest/funds/k33-assets-i-fund-limited
Authorization: Bearer <firebase-id-token>
Content-Type: application/json

{
  "investorType": "PROFESSIONAL",
  "name": "Test",
  "phoneNumber": {
    "countryCode": "47",
    "nationalNumber": "41234567"
  },
  "countryCode": "NOR",
  "fundName": "K33 Assets I Fund Limited"
}

### Get status as HTTP response status code for a given fund

GET https://api.k33.com/apps/invest/funds/k33-assets-i-fund-limited
Authorization: Bearer <firebase-id-token>

### Get status for all funds as map in response body

GET https://api.k33.com/apps/invest/funds
Authorization: Bearer <firebase-id-token>
