### Get all payment subscription products

GET https://api.k33.com/payment/subscribed-products
Authorization: Bearer <firebase-id-token>

###

POST https://api.k33.com/payment/checkout-session
Authorization: Bearer <firebase-id-token>
Content-Type: application/json

{
  "price_id": "",
  "success_url": "",
  "cancel_url": ""
}

###

POST https://api.k33.com/payment/customer-portal-session
Authorization: Bearer <firebase-id-token>
Content-Type: application/json

{
  "return_url": ""
}