### Get legal entry metadata for given T&C ID

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    legalTextCollection (where: { titleOfLegalText: "platform.termsAndConditions" }, limit:10) {
        items {
            titleOfLegalText
            sys {
                id
                spaceId
                environmentId
                publishedVersion
            }
        }
    }
}