object Version {

    // keep this sorted alphabetically
    // const val arrow = "1.0.1"
    const val config4k = "0.4.2"
    const val contentful = "10.5.2"
    const val contentfulRichTextRenderer = "1.2.0"
    const val firebase = "8.1.0"
    const val googleCloudBom = "24.2.0"
    // const val jacksonKotlin = "2.13.0"
    const val jibPlugin = "3.1.4"
    // const val jjwt = "0.11.2"
    const val junit5 = "1.8.2"
    const val kotest = "5.1.0"
    const val kotlin = "1.6.10"
    const val kotlinCoroutines = "1.6.0"
    const val kotlinSerialization = "1.3.2"
    const val ktor = "1.6.7"
    const val logback = "1.2.10"
    const val micrometer = "1.8.2"
    const val micronaut = "4.0.0"
    const val sendgrid = "4.8.2"
    const val slf4j = "1.7.33"
    const val versionsPlugin = "0.41.0"
}
