kind: compute#urlMap
name: http-redirect-url-map
defaultUrlRedirect:
  redirectResponseCode: MOVED_PERMANENTLY_DEFAULT
  httpsRedirect: True
tests:
  - description: Test with no query parameters
    host: example.com
    path: /test/
    expectedOutputUrl: https://example.com/test/
    expectedRedirectResponseCode: 301
  - description: Test with query parameters
    host: example.com
    path: /test/?parameter1=value1&parameter2=value2
    expectedOutputUrl: https://example.com/test/?parameter1=value1&parameter2=value2
    expectedRedirectResponseCode: 301