### Get all reports

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    reportCollection {
        items {
            title
            slug
            subtitle
            description {
                json
            }
            image {
                fileName
                title
                description
                url
            }
            publishDate
            tagsCollection(limit: 10) {
                items {
                    name
                }
            }
            sponsorsCollection(limit: 10) {
                items {
                    name
                    logo
                    {
                        fileName
                        title
                        description
                        url
                    }
                }
            }
            sys {
                id
                publishedAt
            }
        }
    }
}