### Get all tags

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    tagCollection(order: [name_ASC]) {
        items {
            name
            linkedFrom {
                pageWeeklyUpdateCollection(limit: 1) {
                    total
                }
                reportCollection(limit: 1) {
                    total
                }
            }
        }
    }
}