### arcane.no to OPTIONS api.arcane.no

OPTIONS https://api.arcane.no
Origin: https://arcane.no
Access-Control-Request-Method: GET

### arcane.no to GET api.arcane.no

GET https://api.arcane.no/ping
Origin: https://arcane.no

### dev.arcane.no to OPTIONS api.arcane.no

OPTIONS https://api.arcane.no/
Origin: https://dev.arcane.no
Access-Control-Request-Method: GET

### developer.arcane.no to OPTIONS api.arcane.no

OPTIONS https://api.arcane.no
Origin: https://developer.arcane.no
Access-Control-Request-Method: GET

### localhost:3000 to OPTIONS dev.api.arcane.no

OPTIONS https://dev.api.arcane.no
Origin: http://localhost:3000
Access-Control-Request-Method: GET