### get user and array of T&C

GRAPHQL https://api.arcane.no/graphql
Authorization: Bearer
Content-Type: application/graphql

{
    user {
        userId
        analyticsId
    }
    termsAndConditions(tncIds: ["platform.termsAndConditions", "platform.privacyPolicy"]) {
        tncId
        version
        accepted
        spaceId
        entryId
        fieldId
        timestamp
    }
}